version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
     - "dependencies"
     - "no-changelog-needed"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
    labels:
     - "dependencies"
     - "no-changelog-needed"
    groups:
      gradle:
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "com.opencastsoftware:prettier4j"
        versions: [ "0.3.1", "0.3.2" ]
  - package-ecosystem: "pip"
    directories:
      - "/docs"
      - "/.changes"
    schedule:
      interval: "weekly"
      day: "wednesday"
    labels:
     - "dependencies"
     - "no-changelog-needed"
    groups:
      python:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "npm"
    directory: "/docs/landing-page"
    schedule:
      interval: "weekly"
      day: "wednesday"
    labels:
     - "dependencies"
     - "no-changelog-needed"
    groups:
      npm:
        update-types:
          - "minor"
          - "patch"
